### ISSUE TITLE
NoClassDefFoundError for FilterAtomicReader$FilterTerms

### ISSUE THREAD

**Issue by dejon97** [tarzanek/luke#4]
Downloaded "lukeall-5.3.0.jar" from "https://java.net/projects/opengrok/downloads." Ran the following command "java -cp lukeall-5.3.0.jar org.getopt.luke.Luke." When prompted I attempted to open an ElasticSearch index and received the following:

java.lang.NoClassDefFoundError: org/apache/lucene/index/FilterAtomicReader$Filte
rTerms
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14
2)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.elasticsearch.index.codec.postingsformat.BloomFilterPostingsForma
t.fieldsProducer(BloomFilterPostingsFormat.java:99)
.
.
.

It appears that the class "FilterAtomicReader" has been removed from "lucene-core-5.3.0.jar." To get it run, I copied over the classes "FilterAtomicReader" and "AtomicReader" from "lucene-core-4.10.4.jar" into "lucene-core-5.3.0.jar."

**Comment by tarzanek** [comment]
Thnx for the report
This basically means elastic search is not having it's codecs that independant from lucene ver as I originally did hope ...

**Comment by tarzanek** [comment]
What version of elastic search index was used?

**Comment by tarzanek** [comment]
for now I dropped support for any other than  org.elasticsearch.index.codec.postingsformat.Elasticsearch090PostingsFormat
in 5.3.1 luke (just released)
we need to find a way how to support all elasticsearch codecs without mixing up dependencies on lucene (lucene 5.x has a backwards codec jar, wondering if that might contain needed classes?)
alt. is to ping elasticsearch guys to tell us how to do it, or untangle their formats to be readable by newer lucene

**Comment by dejon97** [comment]
Hey taranek, my bad on the delay. The version was ElasticSearch 1.1.2. I'll do some research as time permits. Will keep you updated on any discovers.

**Comment by tarzanek** [comment]
@dejon97 I only tested 1.7.2 and restricted it to Elasticsearch090PostingsFormat only ...
wondering if with 1.1.2 there were even more restrictions ...
but let's see what will happen, maybe 2.0 of ES will be less interconnected

**Comment by tarzanek** [comment]
closing, I upped to es 5.0.0 , now lucene and es are in sync
